pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'bc0569/dev-app' // Docker 이미지 이름
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'http://172.27.0.1:3000/cicd-labs/dev-app.git',  // Git에서 코드 체크아웃
                credentialsId: 'gitea-kkumtree-devops'
            }
        }
        stage('Read VERSION') {
            steps {
                script {
                    // VERSION 파일 읽기
                    def version = readFile('VERSION').trim()
                    echo "Version found: ${version}"
                    // 환경 변수 설정
                    env.DOCKER_TAG = version
                }
            }
        }
        stage('Docker Build and Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-full-access') {
                        // DOCKER_TAG 사용
                        def appImage = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                        appImage.push()
                        appImage.push("latest")
                    }
                }
            }
        }
    }
    post {
        success {
            echo "Docker image ${DOCKER_IMAGE}:${DOCKER_TAG} has been built and pushed successfully!"
        }
        failure {
            echo "Pipeline failed. Please check the logs."
        }
    }
}